Repository USBGuard/usbguard, pull requests merged in 2018-07, with the labels that each got.

#236 Changes that help build usbguard with clang++ and with less dependencies.
  Makefile.am
  configure.ac
  src/Library/public/usbguard/ConfigFile.cpp
  src/Library/public/usbguard/Device.cpp
  src/Library/public/usbguard/DeviceManager.cpp
  src/Library/public/usbguard/IPCClient.cpp
  src/Library/public/usbguard/IPCServer.cpp
  src/Library/public/usbguard/Rule.cpp
  src/Library/public/usbguard/RuleSet.cpp
Labels: enhancement, packaging, usability

#239 Align DBus Interface XML spec
  src/DBus/DBusInterface.xml
Labels: bug

#238 Add alternative to stdio_filebuf.h for libc++ support.
  Makefile.am
  configure.ac
  m4/ax_boost_base.m4
  m4/ax_boost_iostreams.m4
  src/Common/FDInputStream.hpp
Labels: enhancement

#240 Reorder object registration to match interface info/xml order.
  src/DBus/gdbus-server.cpp
Labels: bug

#241 Replace boost dependency with a smaller alternative to stdio_filebuf.h.
  configure.ac
  m4/ax_boost_base.m4
  m4/ax_boost_iostreams.m4
  src/Common/FDInputStream.hpp
Labels: enhancement

#242 Added # line comments to the rule grammar.
  src/Daemon/Daemon.cpp
  src/GUI.Qt/DeviceDialog.cpp
  src/GUI.Qt/MainWindow.cpp
  src/Library/RuleParser/Actions.hpp
  src/Library/RuleParser/Grammar.hpp
  src/Library/UEventDeviceManager.cpp
  src/Library/UMockdevDeviceManager.cpp
  src/Library/public/usbguard/DeviceManager.cpp
  src/Library/public/usbguard/Rule.cpp
  src/Library/public/usbguard/Rule.hpp
  src/Tests/Rules/test-rules.bad
  src/Tests/Rules/test-rules.good
Labels: enhancement, rule language

#244 Added fuzzer targets for oss-fuzz.
  configure.ac
  src/Tests/Fuzzers/Makefile.am
  src/Tests/Fuzzers/fuzzer-rules.cpp
  src/Tests/Fuzzers/fuzzer-uevent.cpp
  src/Tests/Fuzzers/fuzzer-uevent_corpus/0001.bin
  src/Tests/Fuzzers/fuzzer-usb-descriptor.cpp
  src/Tests/Makefile.am
Labels: enhancement, security
